#!/usr/bin/env tsx
/**
 * Generate Verification Report (Markdown)
 *
 * Creates a detailed markdown report from verification results.
 * This report is committed to the `attestation` branch as README.md
 *
 * Part of Phase 2.1: Verifiable Builds
 */

import type { VerificationResult } from './verify-deployment.js';

interface ReportData {
  result: VerificationResult;
  runUrl?: string;
}

/**
 * Format timestamp as human-readable
 */
function formatTimestamp(timestamp: string): string {
  const date = new Date(timestamp);
  return date.toUTCString();
}

/**
 * Generate markdown report from verification result
 */
export function generateReport(data: ReportData): string {
  const { result, runUrl } = data;
  const status = result.allPassed ? '✅ VERIFIED' : '❌ FAILED';
  const statusEmoji = result.allPassed ? '✅' : '❌';

  const report = `# 🔐 KMS Verification Report

## Verification Summary

**Status:** ${status}
**Timestamp:** ${formatTimestamp(result.timestamp)}
**Worker Hash:** ${result.manifest?.current.sha256.substring(0, 8) || 'unknown'}
${runUrl ? `**Workflow Run:** [View Details](${runUrl})` : ''}

---

## About This Report

This report is automatically generated by the [KMS Verifier](https://github.com/lukium/ats-kms/tree/verifier).

The verifier runs approximately **4 times per day** at random times to check that the deployed KMS enclave matches the published manifest and security specifications.

### What Gets Verified:
1. **Manifest Integrity** - Validates manifest structure and accessibility
2. **Hash Verification** - Confirms SHA256 and SRI hashes match for all artifacts
3. **Security Headers** - Verifies CSP, CORP, and other security policies
4. **Allowed List** - Ensures deployed version is in the allowed versions list
5. **Reproducible Build** - Confirms the build can be reproduced from source
6. **GitHub Attestation** - Validates Sigstore attestation via Rekor transparency log

### Trust Model:
- **Verifier Code:** Frozen and auditable at specific commit
- **This Report:** Auto-generated, constantly updated
- **Transparency:** All verification results and attestation URLs are publicly accessible

---

## Verification Details

${result.checks.map(check => {
  const checkStatus = check.passed ? '✅' : '❌';
  let details = '';

  if (check.details) {
    if (check.name === 'Hash Verification' && Array.isArray(check.details)) {
      // Format as table
      details = '\n\n| Artifact | Expected | Actual | Status |\n|----------|----------|--------|--------|\n';
      check.details.forEach((item: any) => {
        const itemStatus = item.passed ? '✅' : '❌';
        details += `| **${item.name}** | \`${item.expected}\` | \`${item.actual}\` | ${itemStatus} |\n`;
      });
    } else if (check.name === 'Worker Hash' && check.details.expected) {
      details = `

**Expected Hash:**
\`\`\`
${check.details.expected}
\`\`\`

**Actual Hash:**
\`\`\`
${check.details.actual}
\`\`\`

**Source:** ${check.details.url}`;
    } else if (check.name === 'SRI Hashes' && Array.isArray(check.details)) {
      details = '\n\n' + check.details.map((d: any) => {
        if (d.expected && d.actual) {
          const status = d.passed ? '✅' : '❌';
          return `#### ${d.name} ${status}

**Expected SRI:**
\`\`\`
${d.expected}
\`\`\`

**Actual SRI:**
\`\`\`
${d.actual}
\`\`\`

**Source:** ${d.url}`;
        } else {
          return `#### ${d.name} ❌

${d.message}`;
        }
      }).join('\n\n');
    } else if (check.name === 'Security Headers' && Array.isArray(check.details)) {
      details = '\n\n' + check.details.map((h: any) => {
        let headerDetails = '';

        // Add CSP frame-ancestors explanation
        if (h.name === 'content-security-policy' && h.passed) {
          headerDetails = `

**Frame Ancestors Explanation:**
The \`frame-ancestors\` directive controls which origins can embed the KMS enclave in an iframe:

- \`https://alpha.allthe.services\` - Development build of the AllTheServices app
- \`https://beta.allthe.services\` - Beta build (not yet available)
- \`https://allthe.services\` - Production build (not yet available)
- \`https://phase2-demo.allthe.services\` - Demo for the KMS enclave itself
- \`http://localhost:5173\` - Local development counterpart of the dev build`;
        }

        if (h.passed) {
          return `#### ${h.name} ✅

**Expected:** \`${h.expected}\`

**Actual:** ✅ Matches${headerDetails}`;
        } else {
          return `#### ${h.name} ❌

**Expected:**
\`\`\`
${h.expected}
\`\`\`

**Actual:**
\`\`\`
${h.actual || '(missing)'}
\`\`\`

**Issue:** ${h.message}`;
        }
      }).join('\n\n');
    } else if (check.name === 'Allowed List' && check.details) {
      details = `

**Current Hash:** \`${check.details.currentHash}\`

**Allowed Hashes:**
${check.details.allowed.map((hash: string) => `- \`${hash}\``).join('\n')}`;
    } else if (check.name === 'Reproducible Build' && check.details) {
      details = `

**Commit:** \`${check.details.commit}\`

**Expected Hash:** \`${check.details.expected}\`

**Actual Hash:** \`${check.details.actual}\`

**Reproduce This Build:**
\`\`\`bash
${check.details.commands ? check.details.commands.join('\n') : '# Commands not available'}
\`\`\`

The hash from the last command should match: \`${check.details.expected}\``;
    } else if (check.name === 'GitHub Attestation' && check.details) {
      let attestationDetails = `

**Artifact:** \`${check.details.artifact}\`

**Commit:** \`${check.details.commit}\``;

      if (check.details.rekorUrl) {
        attestationDetails += `

**Rekor Transparency Log:**
${check.details.rekorUrl}`;
      }

      if (check.details.attestationUrl) {
        attestationDetails += `

**Repository Attestations:**
${check.details.attestationUrl}`;
      }

      details = attestationDetails;
    }
  }

  return `### ${checkStatus} ${check.name}

${check.message}${details}
`;
}).join('\n')}

---

### Manifest Details

${result.manifest ? `\`\`\`json
${JSON.stringify(result.manifest, null, 2)}
\`\`\`` : '*Manifest not available*'}

---

*Last updated: ${formatTimestamp(result.timestamp)}*
*Verifier: [github.com/lukium/ats-kms/tree/verifier](https://github.com/lukium/ats-kms/tree/verifier)*
`;

  return report;
}

/**
 * Main entry point
 */
async function main() {
  const inputFile = process.argv[2];
  const runUrl = process.argv[3];

  if (!inputFile) {
    console.error('Usage: tsx generate-report.ts <verification-result.json> [runUrl]');
    process.exit(1);
  }

  const fs = await import('fs');
  const resultData = JSON.parse(fs.readFileSync(inputFile, 'utf-8'));

  const report = generateReport({
    result: resultData,
    runUrl,
  });

  console.log(report);
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
