#!/usr/bin/env tsx
/**
 * Generate Verification Report (Markdown)
 *
 * Creates a detailed markdown report from verification results.
 * This report is committed to the `attestation` branch as README.md
 *
 * Part of Phase 2.1: Verifiable Builds
 */

import type { VerificationResult } from './verify-deployment.js';

interface ReportData {
  result: VerificationResult;
  runUrl?: string;
}

/**
 * Format timestamp as human-readable
 */
function formatTimestamp(timestamp: string): string {
  const date = new Date(timestamp);
  return date.toUTCString();
}

/**
 * Generate markdown report from verification result
 */
export function generateReport(data: ReportData): string {
  const { result, runUrl } = data;
  const status = result.allPassed ? '✅ VERIFIED' : '❌ FAILED';
  const statusEmoji = result.allPassed ? '✅' : '❌';

  const report = `# 🔐 KMS Verification Report

**Status:** ${status}
**Timestamp:** ${formatTimestamp(result.timestamp)}
**Worker Hash:** ${result.manifest?.current.sha256.substring(0, 8) || 'unknown'}
${runUrl ? `**Workflow Run:** [View Details](${runUrl})` : ''}

---

## Verification Results

${result.checks.map(check => {
  const checkStatus = check.passed ? '✅' : '❌';
  let details = '';

  if (check.details) {
    if (check.name === 'Worker Hash' && check.details.expected) {
      details = `
- **Expected:** \`${check.details.expected}\`
- **Actual:** \`${check.details.actual}\`
- **URL:** ${check.details.url}`;
    } else if (check.name === 'SRI Hashes' && Array.isArray(check.details)) {
      details = '\n' + check.details.map((d: any) =>
        `  - **${d.name}:** ${d.passed ? '✅' : '❌'} ${d.message}`
      ).join('\n');
    } else if (check.name === 'Security Headers' && Array.isArray(check.details)) {
      details = '\n' + check.details.map((h: any) =>
        `  - **${h.name}:** ${h.passed ? '✅' : '❌'} ${h.message || 'OK'}`
      ).join('\n');
    }
  }

  return `### ${checkStatus} ${check.name}

${check.message}${details}
`;
}).join('\n')}

---

## Manifest Details

${result.manifest ? `
- **Version:** ${result.manifest.current.version}
- **Build Time:** ${new Date(parseInt(result.manifest.current.build.SOURCE_DATE_EPOCH) * 1000).toUTCString()}
- **Reproducible:** ${result.manifest.current.build.reproducible ? 'Yes' : 'No'}
- **Environment:** ${result.manifest.current.build.environment}

### Files
- **Worker:** \`${result.manifest.current.files.worker.filename}\`
  - SHA-256: \`${result.manifest.current.files.worker.sha256}\`
  - SRI: \`${result.manifest.current.files.worker.sri}\`

- **Client JS:** \`${result.manifest.current.files.client.filename}\`
  - SRI: \`${result.manifest.current.files.client.sri}\`

- **CSS:** \`${result.manifest.current.files.css.filename}\`
  - SRI: \`${result.manifest.current.files.css.sri}\`

### Allowed Versions
${result.manifest.allowed.map(hash => `- \`${hash.substring(0, 8)}...\``).join('\n')}
` : '*Manifest not available*'}

---

## About This Report

This report is automatically generated by the [KMS Verifier](https://github.com/lukium/ats-kms/tree/verifier).

The verifier runs approximately **4 times per day** at random times to check that the deployed KMS enclave matches the published manifest and security specifications.

### What Gets Verified:
1. Manifest integrity and structure
2. Worker hash matches deployed version
3. SRI (Subresource Integrity) hashes for all resources
4. Security headers (CSP, Permissions-Policy, etc.)
5. Current version is in allowed list
6. [Future] Rekor transparency log attestation

### Trust Model:
- **Verifier Code:** Frozen and auditable at specific commit
- **This Report:** Auto-generated, constantly updated
- **Badge:** Links to this report for transparency

---

*Last updated: ${formatTimestamp(result.timestamp)}*
*Verifier: [github.com/lukium/ats-kms/tree/verifier](https://github.com/lukium/ats-kms/tree/verifier)*
`;

  return report;
}

/**
 * Main entry point
 */
async function main() {
  // This would typically receive the verification result via stdin or file
  console.log('generateReport requires verification result data');
  console.log('Use: echo $JSON | tsx generate-report.ts');
  process.exit(1);
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
